const mbtiInfo = [
    {
        id : 1,
        mbti : "ENFJ",
        comment : "타인의 성장을 도모하고 협동하는 사람",
        good : ["완벽주의", "새로움과 변화를 즐김", "추진력이 있음", "리더 성향", "높은 공감능력"],
        bad : ["지나친 이상주의", "감정 기복이 심함", "갈등과 어려움을 싫어함", "경쟁 환경에서 회피", "목표를 달성하지 못하면 상실감이 매우 큼"],
        work : ["동료 및 고객들과 따뜻하고 서로 도움이 되는 인간관계를 맺을 수 있는 일", "가치 있다고 생각하는 프로젝트의 문제점들에 대해 창의적인 해결책을 제시할 수 있는 일", "나에 대한 기대치가 있고, 나의 공로를 인정해 주며, 업무 능력의 성장과 발전을 격려 받을 수 있는 환경에서 하는 일", "문제점을 창의적으로 해결할 수 있는 충분한 시간이 주어지고, 이에 대해 다른 사람들과 의견을 나눌 수 있는 일", "여러 가지 프로젝트를 한 번에 추진할 수 있는 활동적이고 자극적인 환경에서 하는 일"],
    },
    {
        id : 2,
        mbti : "ENTJ",
        comment : "비전을 가지고 타인을 활력적으로 인도하는 사람",
        good : ["지도력과 통솔력이 있음", "타고난 리더 성향", "솔직함", "완벽주의자", "도전적"],
        bad : ["완고하고 지배적임", "냉정하고 무자비함", "참을성이 없음", "단호함", "감정표현이 매우 솔직함"],
        work : ["기획 및 지도, 통솔할 수 있으며 다른 사람을 감독하고 관리하는 일", "장기적 계획 수립과 창조적 문제 해결이 필요한 일", "지적인 호기심을 자극하는 일", "재미있고 유능하고 힘 있는 다양한 사람들과 만날 수 있는 일", "단계에 맞게 목표를 세우고 달성할 수 있는 일"],
    },
    {
        id : 3,
        mbti : "ENFP",
        comment : "열정적으로 새 관계를 만들어 나가는 사람",
        good : ["상상력과 창의력이 높음", "뛰어난 통찰력과 추진력", "타인에 대한 관심이 많음", "대화 주도 능력이 뛰어남", "높은 적응력"],
        bad : ["집중력 부족", "스트레스를 쉽게 받음", "생각이 많음", "변덕이 심함", "의사결정할 때 충동적"],
        work : ["창의적으로 다양하고 자유로운 환경에서 할 수 있는 일", "재미있고 도전적인 일 기존에 없는 새로운 아이디어, 상품, 서비스 조직을 만들어 내는 일", "기존에 없는 새로운 아이디어, 상품, 서비스 조직을 만들어 내는 일", "수평적 분위기에서 여러 사람과 함께 진행하는 프로젝트를 하는 일", "최소한의 규칙과 규율이 존재하는 일"],
    },
    {
        id : 4,
        mbti : "ENTP",
        comment : "풍부한 상상력으로 새로운 것에 도전하는 사람",
        good : ["분석을 좋아함", "넓은 포용력", "새로움을 추구함", "객관전인 판단력", "열정적"],
        bad : ["끈기가 부족함", "오지랖이 넓음", "계획은 많으나 실천을 안함", "지나치게 솔직함", "집중력 부족"],
        work : ["창조적이고 혁신적인 일을 만들어 내는 일", "재미, 행동, 흥분으로 가득 찬 다양한 상황을 경험할 수 있게 해주는 일", "다양한 사람들, 특히 존경하는 사람들과 만나 지속적으로 교류할 수 있는 일", "논리적인 순서를 따라서 하는 일", "사람들과 깊은 관계를 맺으면서 에너지가 넘치는 환경에서 할 수 있는 일"],
    },
    {
        id : 5,
        mbti : "ESFP",
        comment : "풍부한 상상력으로 새로운 것에 도전하는 사람",
        good : ["사교적임", "새로움을 추구함", "높은 적응력", "타인에 대한 관심이 많음", "대화 주도 능력이 뛰어남"],
        bad : ["쉽게 지루함을 느낌", "거절을 잘 못함", "유리 멘탈", "고집이 셈", "화가 나면 쉽게 감정에 휩싸이고 흥분함"],
        work : ["활동적이고 사교적인 환경에서 많은 사람들과 일할 수 있는 일", "조용하고 딱딱한 환경을 피하고 편안한 분위기에서 하는 일", "정보를 수집해서 새로운 접근으로 문제를 해결할 수 있는 일", "다른 사람들에게 동기 부여를 할 수 있는 일", "재밌고 색다르고 즐길 수 있는 일"],
    },
    {
        id : 6,
        mbti : "ESFJ",
        comment : "친절하고 현실감을 바탕으로 봉사하는 스타일",
        good : ["높은 친화력", "참을성이 높음", "주관이 뚜렷함", "타인에 대한 관심이 많음", "공감능력이 좋음"],
        bad : ["실행력이 부족", "감정 기복이 심함", "반대 의견에 쉽게 상처를 받음", "생각이 너무 많음", "집단의 일을 개인보다 중시함"],
        work : ["사람들에게 현실적 이득을 줄 수 있는 일", "사람들이 공통의 목표를 향해 조화롭게 나아갈 수 있도록 돕는 일", "기대치가 분명하고 객관적인 기준에 따라 자신의 일을 평가 받을 수 있는 일", "존중 받는 조직적인 환경에서 하는 일", "의사 결정 과정에 주체적으로 참여할 수 있는 일"],
    },
    {
        id : 7,
        mbti : "ESTP",
        comment : "친구나 운동 등 다양함을 선호하는 사람",
        good : ["사교적임", "통찰력이 있음", "사람을 이끄는 스타일", "도전을 좋아함", "자존감이 높음"],
        bad : ["자기 주장이 강함", "지나치게 솔직하고 직설적", "참을성이 부족함", "끈기가 부족함", "반항아적 기질"],
        work : ["실질적이고 논리적인 일", "많은 사람들과 자발적으로 만나서 교류할 수 있는 일", "직접 경험과 뛰어난 분석력을 통해서 문제를 해결할 수 있는 일", "위기 상황과 위급한 문제를 적절히 처리할 수 있는 일", "규칙, 규율, 제한이 많지 않은 일"],
    },
    {
        id : 8,
        mbti : "ESTJ",
        comment : "사무적, 실용적이고 현실적인 스타일의 유형",
        good : ["책임감이 강함", "완벽주의", "논리적이고 체계적임", "결단력이 있음", "타고난리더"],
        bad : ["융통성이 없고 완고함", "감정 표현이 어려움", "현실적, 이성적, 직설적", "남에게 관심 없고 나한테만 집중", "공감 능력이 부족함"],
        work : ["논리적인 결과를 위해 시간과 자원을 효율적으로 사용할 수 있는 일", "공정하고 논리적이며 분명하고 객관적인 기준으로 평가받을 수 있는 일", "자기와 타인에 대해 책임을 지면서, 다른 사람과 함께할 수 있는 일", "결정권이 있으며 권한과 책임이 많고 자신의 견해와 경험이 중요하게 생각되는 일", "현실적이고 구체적인 일"],
    },
    {
        id : 9,
        mbti : "INFP",
        comment : "이상적인 세상을  만들려고 하는 사람",
        good : ["상상력과 창의력이 높음", "사려깊음", "높은 공감능력", "높은 통찰력", "감수성이 풍부함"],
        bad : ["고립되기 쉬운 성격", "집중력이 부족함", "새로운 환경에 먼저 나서기를 꺼려함", "감정에 많이 예민함", "단순하고 반복적인 일을 싫어함"],
        work : ["규칙이나 규율이 엄격한 환경이 아닌 창조적이고 따뜻한 일을 만들어 내는 일", "자신의 가치관과 이상을 표현할 수 있는 일", "대중이나 사람들 앞에서 되도록이면 서지 않는 일", "엄격한 실적이나 성과와 마감이 없는 일", "사적인 공간과 남들의 방해를 적게 받는 공간에서 하는 일"],
    },
    {
        id : 10,
        mbti : "INFJ",
        comment : "사람에 관해 뛰어난 통찰력을 가진 사람",
        good : ["인내심이 강함", "너그러움", "화합을 추구함", "신념과 열정이 강함", "나무보다 숲을 보는 편"],
        bad : ["번아웃 경향이 있음", "융통성이 부족함", "지나치게 생각이 많음", "사교를 어려워 함", "비판에 민감함"],
        work : ["새로운 아이디어나 접근 방식을 찾아내서 사람과 함께 성장과 발전을 도울 수 있는 일", "업무시간과 업무환경을 스스로 조정할 수 있는 일", "업무 과정에 큰 영향력을 행사할 수 있고 권한을 가지고 있는 일", "프로젝트를 실행할 때 충분한 시간적 여유가 주어진 일", "공익적 일이나 봉사하는 일에 아이디어를 쓸 수 있는 일"],
    },
    {
        id : 11,
        mbti : "INTP",
        comment : "비평적인 관점을 가진 뛰어난 전략가",
        good : ["상상력과 창의력이 높음", "논리적,분석적임", "관심있는 분야에 적극적", "개인적인 시간이 중요함", "문제 해결에 효율적임"],
        bad : ["타인과 소통이 어려움", "매사에 진지한 경향이 있음", "팩트 폭격기", "게으르고 잘 미룸", "낯가림이 심함"],
        work : ["아이디어를 개발하고, 분석하고, 비판하는 일", "복잡한 문제를 다룰 수 있는 일", "개인 시간이 많고 독립적으로 할 수 있는 일", "지나친 규칙과 회의가 없는 환경", "사람들을 직접 조직하거나 감독하지 않아도 되는 일"],
    },
    {
        id : 12,
        mbti : "ISTP",
        comment : "논리적이고 뛰어난 상황 적응력",
        good : ["효율을 중요시함", "위기대처 능력이 있음", "객관적인 판단", "적응력이 뛰어남", "현실주의자"],
        bad : ["성격 알기가 어려움", "쉽게 지루함을 느낌", "고집이 세고 주관이 뚜렷함", "감정 표현이 서툼", "타인의 일에 무관심"],
        work : ["목표의 방향성이 뚜렷한 일", "독립적으로 할 수 있고 밖으로 자주 다니는 일", "다른 사람들을 철저히 감독할 필요가 없는 일", "쓸데없는 것에 에너지를 쏟지 않는 일", "재미있고 활동적인 일"],
    },
    {
        id : 13,
        mbti : "ISFP",
        comment : "따뜻한 감성을 가진 겸손한 사람",
        good : ["적응력이 뛰어남", "공감 능력이 뛰어남", "조화를 중요시 함", "배려를 잘함", "넓은 포용력과 이해심"],
        bad : ["만사가 귀찮음", "결단력, 추진력이 부족", "장기적인 약속과 계획을 싫어함", "쉽게 스트레스 받음", "일을 끝까지 미룸"],
        work : ["팀원들과 성실하고 좋은 분위기에서 사람들과 함께 하는 일", "세심하고 주의력이 필요하고 헌신할 수 있는 일", "밝고 협조적인 환경에서 갈등이 거의 없는 일", "실질적인 도움을 제공해서 재빨리 문제를 해결할 수 있는 일", "대중 앞에 서지 않고 잘 모르는 집단을 지도하거나 낯선 사람을 만나지 않는 일"],
    },
    {
        id : 14,
        mbti : "ISFJ",
        comment : "성실하고 온화하며 협조를 잘하는 사람",
        good : ["인내심이 강함", "공감 능력이 뛰어남", "열정적이고 헌신적", "일관적임", "완벽주의 성향이 있음"],
        bad : ["변화를 꺼려함", "본인 얘기를 안함", "거절을 못함", "인간관계에서 상처, 스트레스를 많이 받음", "개인적인 판단으로 생각을 많이함"],
        work : ["세심한 관찰력과 정확성이 요구되는 일", "뒤에서 일하면서 내 헌신과 공감을 표현할 수 있는 일", "한 번에 하나의 프로젝트를 할 수 있는 일", "사적인 공간이 있어서 주의에 방해받지 않고 완전히 집중할 수 있는 일", "사전에 준비할 시간이 충분한 일"],
    },
    {
        id : 15,
        mbti : "ISTJ",
        comment : "한 번 시작한 일은 끝까지 해내는 성격",
        good : ["높은 책임감", "정확하고 철저함", "완벽주의 성향", "원리원칙을 중요시함", "체계적임"],
        bad : ["항상 명확한 규칙에 의해 행동", "새로운 것을 시도하기 꺼려함", "낯가림이 심한편", "사고방식이 로봇 같음", "겉보기에 차가워 보임"],
        work : ["스스로 목표를 세우고 추진할 수 있는 일", "뛰어난 집중력을 이용하여 임무를 완수하는 일", "결과가 눈에 보이고 측정, 예측이 가능한 일", "자신의 현실적 판단과 경험을 높이 평하고 보상해 주는 환경에서 하는 일", "목표가 분명하고 조직의 체계가 명확한 일"],
    },
    {
        id : 16,
        mbti : "INTJ",
        comment : "전체를 조합하여 비전을 제시하는 사람",
        good : ["논리적임", "성취욕이 강함", "높은 직관력", "통찰력", "완벽주의 성향"],
        bad : ["고집이 세고 융통성이 부족", "지나치게 비판적", "혼자서 모든 것을 해결하려는 의지가 강함", "공감 능력이 부족", "타인에게 관심이 없음"],
        work : ["시스템을 혁신적이고 독창적으로 해결책을 개발해 내는 일", "세세하고 반복적인 것을 요구하지 않는 일", "전문성을 갖춘 동료와 함께 할 수 있는 일", "주어진 보상이 논리적인 곳에서 하는 일", "독창적으로 권한이 주어지는 일 "],
    },
];

const matchingInfo = [
    {
        id : 1,
        mbti1 : "ENFJ",
        mbti2 : "ENFJ",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 2,
        mbti1 : "ENFJ",
        mbti2 : "ENTJ",
        content : "상대방은 악의가 없어요! 조금만 이해해볼까요?",
    },
    {
        id : 3,
        mbti1 : "ENFJ",
        mbti2 : "ENFP",
        content : "틀에 얽매이는 것을 싫어해요! 제한보다는 자유를 주세요",
    },
    {
        id : 4,
        mbti1 : "ENFJ",
        mbti2 : "ENTP",
        content : "지치지 않게 힘을 북돋아 주세요!",
    },
    {
        id : 5,
        mbti1 : "ENFJ",
        mbti2 : "ESFP",
        content : "우리팀의 연예인! 자유로움을 이해해줘요",
    },
    {
        id : 6,
        mbti1 : "ENFJ",
        mbti2 : "ESFJ",
        content : "상대방 의견을 존중해주세요!",
    },
    {
        id : 7,
        mbti1 : "ENFJ",
        mbti2 : "ESTP",
        content : "상대방은 기분 나쁜 게 아니에요! 기분 최상:)",
    },
    {
        id : 8,
        mbti1 : "ENFJ",
        mbti2 : "ESTJ",
        content : "감정 표현은 서툴 수 있지만, 책임감이 강한 사람이에요!",
    },
    {
        id : 9,
        mbti1 : "ENFJ",
        mbti2 : "INFP",
        content : "먼저 말을 건네볼까요? 좋은 아침이야:)",
    },
    {
        id : 10,
        mbti1 : "ENFJ",
        mbti2 : "INFJ",
        content : "생각이 다를 때는 천천히 맞춰볼까요?",
    },
    {
        id : 11,
        mbti1 : "ENFJ",
        mbti2 : "INTP",
        content : "개인적인 시간을 충분히 주세요!",
    },
    {
        id : 12,
        mbti1 : "ENFJ",
        mbti2 : "ISTP",
        content : "감정 표현이 서툴 수 있어요! 조금만 이해해 볼까요?",
    },
    {
        id : 13,
        mbti1 : "ENFJ",
        mbti2 : "ISFP",
        content : "지치지 않게 힘을 북돋아 주세요!",
    },
    {
        id : 14,
        mbti1 : "ENFJ",
        mbti2 : "ISFJ",
        content : "누구보다 성실하니 끝까지 믿어주세요!",
    },
    {
        id : 15,
        mbti1 : "ENFJ",
        mbti2 : "ISTJ",
        content : "감정 표현이 서툴 수 있어요! 조금만 이해해 볼까요?",
    },
    {
        id : 16,
        mbti1 : "ENFJ",
        mbti2 : "INTJ",
        content : "독립심이 강한 사람이에요! 관심보다는 여유를 주는 게 어떨까요?",
    },
    {
        id : 17,
        mbti1 : "ENTJ",
        mbti2 : "ENFJ",
        content : "이야기를 듣고 공감부터 해주세요!",
    },
    {
        id : 18,
        mbti1 : "ENTJ",
        mbti2 : "ENTJ",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 19,
        mbti1 : "ENTJ",
        mbti2 : "ENFP",
        content : "생각할 시간이 필요해요! 조금만 여유를 주세요",
    },
    {
        id : 20,
        mbti1 : "ENTJ",
        mbti2 : "ENTP",
        content : "집중해서 끝까지 일을 마무리할 수 있게 도와주세요!",
    },
    {
        id : 21,
        mbti1 : "ENTJ",
        mbti2 : "ESFP",
        content : "지나치게 솔직한 표현은 상처를 줄 수 있어요!",
    },
    {
        id : 22,
        mbti1 : "ENTJ",
        mbti2 : "ESFJ",
        content : "의견을 먼저 내세우기 보다는 이야기를 들어주는 것이 중요해요!",
    },
    {
        id : 23,
        mbti1 : "ENTJ",
        mbti2 : "ESTP",
        content : "집중해서 끝까지 일을 마무리할 수 있게 도와주세요!",
    },
    {
        id : 24,
        mbti1 : "ENTJ",
        mbti2 : "ESTJ",
        content : "논리적으로 말해주면 좋아해요!",
    },
    {
        id : 25,
        mbti1 : "ENTJ",
        mbti2 : "INFP",
        content : "솔직함보다는 공감을 앞세워주세요!",
    },
    {
        id : 26,
        mbti1 : "ENTJ",
        mbti2 : "INFJ",
        content : "통솔 받기보다는 화합하기를 좋아해요!",
    },
    {
        id : 27,
        mbti1 : "ENTJ",
        mbti2 : "INTP",
        content : "낯가림이 심해요! 지나친 사교는 오히려 독이 됩니다",
    },
    {
        id : 28,
        mbti1 : "ENTJ",
        mbti2 : "ISTP",
        content : "판단 능력이 뛰어나요! 의견에 귀를 기울여주세요",
    },
    {
        id : 29,
        mbti1 : "ENTJ",
        mbti2 : "ISFP",
        content : "통솔 받기보다는 화합하기를 좋아해요!",
    },
    {
        id : 30,
        mbti1 : "ENTJ",
        mbti2 : "ISFJ",
        content : "이야기를 듣고 공감부터 해주세요!",
    },
    {
        id : 31,
        mbti1 : "ENTJ",
        mbti2 : "ISTJ",
        content : "낯가림이 심해요! 지나친 사교는 오히려 독이 됩니다",
    },
    {
        id : 32,
        mbti1 : "ENTJ",
        mbti2 : "INTJ",
        content : "성취욕이 강해요! 서로 의지하면 좋은 결과를 얻을 수 있어요:)",
    },
    {
        id : 33,
        mbti1 : "ENFP",
        mbti2 : "ENFJ",
        content : "칭찬을 아끼지 마세요!",
    },
    {
        id : 34,
        mbti1 : "ENFP",
        mbti2 : "ENTJ",
        content : "감정 표현이 서툴 수 있어요! 조금만 이해해 볼까요?",
    },
    {
        id : 35,
        mbti1 : "ENFP",
        mbti2 : "ENFP",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 36,
        mbti1 : "ENFP",
        mbti2 : "ENTP",
        content : "지치지 않게 힘을 북돋아 주세요!",
    },
    {
        id : 37,
        mbti1 : "ENFP",
        mbti2 : "ESFP",
        content : "지치지 않게 힘을 북돋아 주세요!",
    },
    {
        id : 38,
        mbti1 : "ENFP",
        mbti2 : "ESFJ",
        content : "지치지 않게 힘을 북돋아 주세요!",
    },
    {
        id : 39,
        mbti1 : "ENFP",
        mbti2 : "ESTP",
        content : "상대방은 기분 나쁜 게 아니에요! 기분 최상:)",
    },
    {
        id : 40,
        mbti1 : "ENFP",
        mbti2 : "ESTJ",
        content : "감정 표현이 서툴 수 있어요! 조금만 이해해 볼까요?",
    },
    {
        id : 41,
        mbti1 : "ENFP",
        mbti2 : "INFP",
        content : "먼저 말을 건네볼까요? 밥은 먹었니?",
    },
    {
        id : 42,
        mbti1 : "ENFP",
        mbti2 : "INFJ",
        content : "생각할 시간이 필요해요! 조금만 여유를 주세요",
    },
    {
        id : 43,
        mbti1 : "ENFP",
        mbti2 : "INTP",
        content : "낯가림이 심해요! 지나친 사교는 오히려 독이 됩니다",
    },
    {
        id : 44,
        mbti1 : "ENFP",
        mbti2 : "ISTP",
        content : "감정 표현이 서툴 수 있어요! 조금만 이해해 볼까요?",
    },
    {
        id : 45,
        mbti1 : "ENFP",
        mbti2 : "ISFP",
        content : "미래보다는 현상을 중요하게 생각해요!",
    },
    {
        id : 46,
        mbti1 : "ENFP",
        mbti2 : "ISFJ",
        content : "지치지 않게 힘을 북돋아 주세요!",
    },
    {
        id : 47,
        mbti1 : "ENFP",
        mbti2 : "ISTJ",
        content : "낯가림이 심해요! 지나친 사교는 오히려 독이 됩니다",
    },
    {
        id : 48,
        mbti1 : "ENFP",
        mbti2 : "INTJ",
        content : "로.봇.이.라.고 놀리지 말아요! 마음은 누구보다 따뜻해요:)",
    },
    {
        id : 49,
        mbti1 : "ENTP",
        mbti2 : "ENFJ",
        content : "솔직함보다는 공감을 앞세워주세요!",
    },
    {
        id : 50,
        mbti1 : "ENTP",
        mbti2 : "ENTJ",
        content : "타고난 리더에요! 협조하면 긍정적인 시너지가 날 거예요",
    },
    {
        id : 51,
        mbti1 : "ENTP",
        mbti2 : "ENFP",
        content : "논쟁하기 보다는 의견에 먼저 귀를 기울여주세요!",
    },
    {
        id : 52,
        mbti1 : "ENTP",
        mbti2 : "ENTP",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 53,
        mbti1 : "ENTP",
        mbti2 : "ESFP",
        content : "공감을 바탕으로 대화를 나누면 좋은 아이디어를 얻을 수 있어요!",
    },
    {
        id : 54,
        mbti1 : "ENTP",
        mbti2 : "ESFJ",
        content : "주관이 뚜렷한 편이에요! 논리보다는 존중이 필요합니다",
    },
    {
        id : 55,
        mbti1 : "ENTP",
        mbti2 : "ESTP",
        content : "미래보다는 현상을 중요하게 생각해요",
    },
    {
        id : 56,
        mbti1 : "ENTP",
        mbti2 : "ESTJ",
        content : "타고난 리더십이 있어요! 믿고 의지하면 좋은 결과를 얻을 수 있어요",
    },
    {
        id : 57,
        mbti1 : "ENTP",
        mbti2 : "INFP",
        content : "지나친 관심은 오히려 독이 될 수 있어요!",
    },
    {
        id : 58,
        mbti1 : "ENTP",
        mbti2 : "INFJ",
        content : "통솔 받기보다는 화합하기를 좋아해요!",
    },
    {
        id : 59,
        mbti1 : "ENTP",
        mbti2 : "INTP",
        content : "뛰어난 분석력이 있으니 관심보다는 믿음을 주세요!",
    },
    {
        id : 60,
        mbti1 : "ENTP",
        mbti2 : "ISTP",
        content : "추상적인 생각보다는 현실적인 의견을 앞세워 말해주면 좋아해요!",
    },
    {
        id : 61,
        mbti1 : "ENTP",
        mbti2 : "ISFP",
        content : "낯가림이 있지만 적응력은 뛰어나요! 약간의 여유를 주면 어떨까요?",
    },
    {
        id : 62,
        mbti1 : "ENTP",
        mbti2 : "ISFJ",
        content : "집중할 수 있는 환경을 조성해 주면 좋은 결과를 얻을 수 있어요!",
    },
    {
        id : 63,
        mbti1 : "ENTP",
        mbti2 : "ISTJ",
        content : "독립심이 강한 사람이에요! 스스로 추진력이 강하니 과한 오지랖은 금물!",
    },
    {
        id : 64,
        mbti1 : "ENTP",
        mbti2 : "INTJ",
        content : "독립심이 강한 사람이에요! 스스로 추진력이 강하니 과한 오지랖은 금물!",
    },
    {
        id : 65,
        mbti1 : "ESFP",
        mbti2 : "ENFJ",
        content : "상대방의 생각을 존중해주세요!",
    },
    {
        id : 66,
        mbti1 : "ESFP",
        mbti2 : "ENTJ",
        content : "상대방의 생각을 존중해주세요!",
    },
    {
        id : 67,
        mbti1 : "ESFP",
        mbti2 : "ENFP",
        content : "생각이 다르더라도 우리 천천히 맞춰볼까요?",
    },
    {
        id : 68,
        mbti1 : "ESFP",
        mbti2 : "ENTP",
        content : "창의력이 뛰어나요! 북돋아 주면 좋은 아이디어를 얻을 수 있어요",
    },
    {
        id : 69,
        mbti1 : "ESFP",
        mbti2 : "ESFP",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 70,
        mbti1 : "ESFP",
        mbti2 : "ESFJ",
        content : "상대방의 의견을 존중해 주세요!",
    },
    {
        id : 71,
        mbti1 : "ESFP",
        mbti2 : "ESTP",
        content : "상대방의 의견도 한 번 들어볼까요?",
    },
    {
        id : 72,
        mbti1 : "ESFP",
        mbti2 : "ESTJ",
        content : "감정 표현은 서툴 수 있지만, 책임감이 강한 사람이에요!",
    },
    {
        id : 73,
        mbti1 : "ESFP",
        mbti2 : "INFP",
        content : "상대방의 상상력을 존중해주세요!",
    },
    {
        id : 74,
        mbti1 : "ESFP",
        mbti2 : "INFJ",
        content : "상상력과 창의력이 뛰어나요! 아이디어가 필요할 때 도움을 청해보세요",
    },
    {
        id : 75,
        mbti1 : "ESFP",
        mbti2 : "INTP",
        content : "낯가림이 심해요! 지나친 사교는 오히려 독이 됩니다",
    },
    {
        id : 76,
        mbti1 : "ESFP",
        mbti2 : "ISTP",
        content : "감정 표현이 서툴 수 있어요! 조금만 이해해 볼까요?",
    },
    {
        id : 77,
        mbti1 : "ESFP",
        mbti2 : "ISFP",
        content : "거시적인 안목이 탁월해요! 장기적인 계획을 세울 때 분명 도움이 될 거예요",
    },
    {
        id : 78,
        mbti1 : "ESFP",
        mbti2 : "ISFJ",
        content : "오늘도 말을 예쁘게 건네볼까요? 잘잤니?",
    },
    {
        id : 79,
        mbti1 : "ESFP",
        mbti2 : "ISTJ",
        content : "로.봇.이.라.고 놀리지 말아요! 마음은 누구보다 따뜻해요:)",
    },
    {
        id : 80,
        mbti1 : "ESFP",
        mbti2 : "INTJ",
        content : "독립심이 강한 사람이에요! 관심보다는 여유를 주는 게 어떨까요?",
    },
    {
        id : 81,
        mbti1 : "ESFJ",
        mbti2 : "ENFJ",
        content : "창의적으로 해결할 수 있는 능력이 강해요! 생각할 시간을 충분히 주세요",
    },
    {
        id : 82,
        mbti1 : "ESFJ",
        mbti2 : "ENTJ",
        content : "타고난 리더에요! 논리적으로 문제 해결하는 것을 좋아해요",
    },
    {
        id : 83,
        mbti1 : "ESFJ",
        mbti2 : "ENFP",
        content : "창의력이 뛰어나요! 북돋아 주면 좋은 아이디어를 얻을 수 있어요",
    },
    {
        id : 84,
        mbti1 : "ESFJ",
        mbti2 : "ENTP",
        content : "논리적인 순서에 따라 일하는 환경을 좋아해요!",
    },
    {
        id : 85,
        mbti1 : "ESFJ",
        mbti2 : "ESFP",
        content : "자유로운 환경 속에서 일의 능률이 올라요! 제한하기보다는 자유를 주세요",
    },
    {
        id : 86,
        mbti1 : "ESFJ",
        mbti2 : "ESFJ",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 87,
        mbti1 : "ESFJ",
        mbti2 : "ESTP",
        content : "집중해서 끝까지 일을 마무리할 수 있게 도와주세요!",
    },
    {
        id : 88,
        mbti1 : "ESFJ",
        mbti2 : "ESTJ",
        content : "감정 표현은 서툴 수 있지만, 책임감이 강한 사람이에요!",
    },
    {
        id : 89,
        mbti1 : "ESFJ",
        mbti2 : "INFP",
        content : "지나친 관심은 오히려 독이 될 수 있어요!",
    },
    {
        id : 90,
        mbti1 : "ESFJ",
        mbti2 : "INFJ",
        content : "지나친 관심은 오히려 독이 될 수 있어요!",
    },
    {
        id : 91,
        mbti1 : "ESFJ",
        mbti2 : "INTP",
        content : "가벼운 대화보다는 진지한 대화를 좋아해요!",
    },
    {
        id : 92,
        mbti1 : "ESFJ",
        mbti2 : "ISTP",
        content : "목표가 뚜렷하고, 효율을 중시해요! 제한보다는 자유를 주세요",
    },
    {
        id : 93,
        mbti1 : "ESFJ",
        mbti2 : "ISFP",
        content : "집중해서 끝까지 일을 마무리할 수 있게 도와주세요!",
    },
    {
        id : 94,
        mbti1 : "ESFJ",
        mbti2 : "ISFJ",
        content : "집중할 수 있는 환경을 조성해 주면 좋은 결과를 얻을 수 있어요!",
    },
    {
        id : 95,
        mbti1 : "ESFJ",
        mbti2 : "ISTJ",
        content : "독립심이 강한 사람이에요! 관심보다는 여유를 주는 게 어떨까요?",
    },
    {
        id : 96,
        mbti1 : "ESFJ",
        mbti2 : "INTJ",
        content : "독립심이 강한 사람이에요! 관심보다는 여유를 주는 게 어떨까요?",
    },
    {
        id : 97,
        mbti1 : "ESTP",
        mbti2 : "ENFJ",
        content : "너무 솔직한 감정 표현은 상처를 줄 수 있어요",
    },
    {
        id : 98,
        mbti1 : "ESTP",
        mbti2 : "ENTJ",
        content : "창의력이 뛰어나요! 아이디어가 필요할 때 도움을 청해보세요",
    },
    {
        id : 99,
        mbti1 : "ESTP",
        mbti2 : "ENFP",
        content : "생각이 많아 보일 때 넌지시 한 마디 건네주세요!",
    },
    {
        id : 100,
        mbti1 : "ESTP",
        mbti2 : "ENTP",
        content : "상상력과 창의력이 뛰어나요! 아이디어가 필요할 때 도움을 청해보세요",
    },
    {
        id : 101,
        mbti1 : "ESTP",
        mbti2 : "ESFP",
        content : "상냥한 말로 우호적인 분위기를 만들어 보면 어떨까요?",
    },
    {
        id : 102,
        mbti1 : "ESTP",
        mbti2 : "ESFJ",
        content : "상대방의 의견을 존중해 주세요!",
    },
    {
        id : 103,
        mbti1 : "ESTP",
        mbti2 : "ESTP",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 104,
        mbti1 : "ESTP",
        mbti2 : "ESTJ",
        content : "감정 표현이 서툴 수 있어요! 조금만 이해해 볼까요?",
    },
    {
        id : 105,
        mbti1 : "ESTP",
        mbti2 : "INFP",
        content : "상냥한 말투로 먼저 다가가 주세요!",
    },
    {
        id : 106,
        mbti1 : "ESTP",
        mbti2 : "INFJ",
        content : "지나친 관심은 오히려 독이 될 수 있어요!",
    },
    {
        id : 107,
        mbti1 : "ESTP",
        mbti2 : "INTP",
        content : "낯가림이 심해요! 지나친 사교는 오히려 독이 됩니다",
    },
    {
        id : 108,
        mbti1 : "ESTP",
        mbti2 : "ISTP",
        content : "감정 표현이 서툴 수 있어요! 조금만 이해해 볼까요?",
    },
    {
        id : 109,
        mbti1 : "ESTP",
        mbti2 : "ISFP",
        content : "지치지 않게 힘을 북돋아 주세요!",
    },
    {
        id : 110,
        mbti1 : "ESTP",
        mbti2 : "ISFJ",
        content : "직설적인 표현을 조금만 자제해볼까요?",
    },
    {
        id : 111,
        mbti1 : "ESTP",
        mbti2 : "ISTJ",
        content : "감정 표현이 서툴 수 있어요! 조금만 이해해 볼까요?",
    },
    {
        id : 112,
        mbti1 : "ESTP",
        mbti2 : "INTJ",
        content : "낯가림이 심해요! 지나친 사교는 오히려 독이 됩니다",
    },
    {
        id : 113,
        mbti1 : "ESTJ",
        mbti2 : "ENFJ",
        content : "너무 솔직한 감정 표현은 상처를 줄 수 있어요!",
    },
    {
        id : 114,
        mbti1 : "ESTJ",
        mbti2 : "ENTJ",
        content : "거시적인 안목이 탁월해요! 장기적인 계획을 세울 때 분명 도움이 될 거예요",
    },
    {
        id : 115,
        mbti1 : "ESTJ",
        mbti2 : "ENFP",
        content : "틀에 얽매이는 것을 싫어해요! 제한보다는 자유를 주세요",
    },
    {
        id : 116,
        mbti1 : "ESTJ",
        mbti2 : "ENTP",
        content : "집중해서 끝까지 일을 마무리할 수 있게 도와주세요!",
    },
    {
        id : 117,
        mbti1 : "ESTJ",
        mbti2 : "ESFP",
        content : "틀에 얽매이는 것을 싫어해요! 제한보다는 자유를 주세요",
    },
    {
        id : 118,
        mbti1 : "ESTJ",
        mbti2 : "ESFJ",
        content : "의견을 먼저 내세우기 보다는 이야기를 들어주는 것이 중요해요!",
    },
    {
        id : 119,
        mbti1 : "ESTJ",
        mbti2 : "ESTP",
        content : "자유로운 환경 속에서 일의 능률이 올라요! 제한하기보다는 자유를 주세요",
    },
    {
        id : 120,
        mbti1 : "ESTJ",
        mbti2 : "ESTJ",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 121,
        mbti1 : "ESTJ",
        mbti2 : "INFP",
        content : "솔직함보다는 공감을 앞세워주세요!",
    },
    {
        id : 122,
        mbti1 : "ESTJ",
        mbti2 : "INFJ",
        content : "새로운 방식으로 접근하는 것을 좋아해요! 의견을 존중해 주는 것이 어떨까요?",
    },
    {
        id : 123,
        mbti1 : "ESTJ",
        mbti2 : "INTP",
        content : "관심 분야는 누구보다 적극적이에요! 여유를 주면 좋은 아이디어를 얻을 수 있을 거예요",
    },
    {
        id : 124,
        mbti1 : "ESTJ",
        mbti2 : "ISTP",
        content : "자유로운 환경 속에서 일의 능률이 올라요! 제한하기보다는 자유를 주세요",
    },
    {
        id : 125,
        mbti1 : "ESTJ",
        mbti2 : "ISFP",
        content : "협력과 조화를 중요하게 생각해요! 서로 배려해보는 게 어떨까요?",
    },
    {
        id : 126,
        mbti1 : "ESTJ",
        mbti2 : "ISFJ",
        content : "지나치게 솔직한 표현은 상처를 줄 수 있어요!",
    },
    {
        id : 127,
        mbti1 : "ESTJ",
        mbti2 : "ISTJ",
        content : "논리만 내세우기보다는 의견을 존중해주세요!",
    },
    {
        id : 128,
        mbti1 : "ESTJ",
        mbti2 : "INTJ",
        content : "성취욕이 강한 사람이에요! 서로 의지하면 좋은 결과를 얻을 수 있어요!",
    },
    {
        id : 129,
        mbti1 : "INFP",
        mbti2 : "ENFJ",
        content : "생각이 많아 보일 때 넌지시 한 마디 건네주세요!",
    },
    {
        id : 130,
        mbti1 : "INFP",
        mbti2 : "ENTJ",
        content : "긍정적 사고를 전파해주세요!",
    },
    {
        id : 131,
        mbti1 : "INFP",
        mbti2 : "ENFP",
        content : "스트레스가 많아 보일 때 공감과 위로를 해주세요!",
    },
    {
        id : 132,
        mbti1 : "INFP",
        mbti2 : "ENTP",
        content : "논리적인 사고를 존중해주세요!",
    },
    {
        id : 133,
        mbti1 : "INFP",
        mbti2 : "ESFP",
        content : "관심이 많아서 그런 거예요! 놀라지 말아요",
    },
    {
        id : 134,
        mbti1 : "INFP",
        mbti2 : "ESFJ",
        content : "생각이 많아 보일 때 넌지시 한 마디 건네주세요!",
    },
    {
        id : 135,
        mbti1 : "INFP",
        mbti2 : "ESTP",
        content : "상대방의 도전을 응원해주세요!",
    },
    {
        id : 136,
        mbti1 : "INFP",
        mbti2 : "ESTJ",
        content : "창의적인 아이디어로 도움을 주세요!",
    },
    {
        id : 137,
        mbti1 : "INFP",
        mbti2 : "INFP",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 138,
        mbti1 : "INFP",
        mbti2 : "INFJ",
        content : "생각이 많아 보일 때 넌지시 한 마디 건네주세요!",
    },
    {
        id : 139,
        mbti1 : "INFP",
        mbti2 : "INTP",
        content : "개인적인 시간을 충분히 주세요!",
    },
    {
        id : 140,
        mbti1 : "INFP",
        mbti2 : "ISTP",
        content : "감정 표현이 서툴 수 있어요! 조금만 이해해 볼까요?",
    },
    {
        id : 141,
        mbti1 : "INFP",
        mbti2 : "ISFP",
        content : "미래보다는 현상을 중요하게 생각해요!",
    },
    {
        id : 142,
        mbti1 : "INFP",
        mbti2 : "ISFJ",
        content : "논쟁보다는 공감을 해주세요!",
    },
    {
        id : 143,
        mbti1 : "INFP",
        mbti2 : "ISTJ",
        content : "목표가 분명한 사람이에요! 이상보다는 현상에 집중해주세요",
    },
    {
        id : 144,
        mbti1 : "INFP",
        mbti2 : "INTJ",
        content : "논리적인 사고를 존중해 주세요!",
    },
    {
        id : 145,
        mbti1 : "INFJ",
        mbti2 : "ENFJ",
        content : "추진력이 강한 사람이에요! 본인의 생각을 한 번 건네보는게 어떨까요?",
    },
    {
        id : 146,
        mbti1 : "INFJ",
        mbti2 : "ENTJ",
        content : "변화를 즐기는 사람이에요! 아이디어를 나누면 좋은 시너지를 낼 수 있을 거예요",
    },
    {
        id : 147,
        mbti1 : "INFJ",
        mbti2 : "ENFP",
        content : "집중해서 끝까지 일을 마무리할 수 있게 도와주세요!",
    },
    {
        id : 148,
        mbti1 : "INFJ",
        mbti2 : "ENTP",
        content : "창의적이고 혁신적인 일을 좋아해요! 의견을 존중해주세요",
    },
    {
        id : 149,
        mbti1 : "INFJ",
        mbti2 : "ESFP",
        content : "낙천적인 사람이에요! 관심을 한 번 표현해 주면 어떨까요?",
    },
    {
        id : 150,
        mbti1 : "INFJ",
        mbti2 : "ESFJ",
        content : "사람을 좋아하고 화합을 추구합니다! 관심을 한 번 표현해 주면 어떨까요?",
    },
    {
        id : 151,
        mbti1 : "INFJ",
        mbti2 : "ESTP",
        content : "집중해서 끝까지 일을 마무리할 수 있게 도와주세요!",
    },
    {
        id : 152,
        mbti1 : "INFJ",
        mbti2 : "ESTJ",
        content : "논리적으로 말해주면 좋아해요!",
    },
    {
        id : 153,
        mbti1 : "INFJ",
        mbti2 : "INFP",
        content : "자신에 대한 관심이 제일 커요! 개성을 존중해주세요",
    },
    {
        id : 154,
        mbti1 : "INFJ",
        mbti2 : "INFJ",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 155,
        mbti1 : "INFJ",
        mbti2 : "INTP",
        content : "분석하는 것을 좋아하는 사람이에요! 계획적으로 실행할 수 있도록 옆에서 도와주세요",
    },
    {
        id : 156,
        mbti1 : "INFJ",
        mbti2 : "ISTP",
        content : "자유로운 환경 속에서 일의 능률이 올라요! 제한하기보다는 자유를 주세요",
    },
    {
        id : 157,
        mbti1 : "INFJ",
        mbti2 : "ISFP",
        content : "집중해서 끝까지 일을 마무리할 수 있게 도와주세요!",
    },
    {
        id : 158,
        mbti1 : "INFJ",
        mbti2 : "ISFJ",
        content : "협조적인 사람이에요! 세심함이 요구되는 일에 도움을 청해보세요",
    },
    {
        id : 159,
        mbti1 : "INFJ",
        mbti2 : "ISTJ",
        content : "목표가 분명한 사람이에요! 이상보다는 현상에 집중해주세요",
    },
    {
        id : 160,
        mbti1 : "INFJ",
        mbti2 : "INTJ",
        content : "주관이 뚜렷한 편이에요! 의견을 존중해 주세요:)",
    },
    {
        id : 161,
        mbti1 : "INTP",
        mbti2 : "ENFJ",
        content : "상냥한 말로 우호적인 분위기를 만들어 보면 어떨까요?",
    },
    {
        id : 162,
        mbti1 : "INTP",
        mbti2 : "ENTJ",
        content : "상대방의 생각을 존중해주세요!",
    },
    {
        id : 163,
        mbti1 : "INTP",
        mbti2 : "ENFP",
        content : "논쟁하기 보다는 의견에 먼저 귀를 기울여주세요!",
    },
    {
        id : 164,
        mbti1 : "INTP",
        mbti2 : "ENTP",
        content : "관심이 많아서 그런 거예요! 놀라지 말아요",
    },
    {
        id : 165,
        mbti1 : "INTP",
        mbti2 : "ESFP",
        content : "가끔씩 먼저 가벼운 농담을 건네보아요!",
    },
    {
        id : 166,
        mbti1 : "INTP",
        mbti2 : "ESFJ",
        content : "가끔씩 먼저 가벼운 농담을 건네보아요!",
    },
    {
        id : 167,
        mbti1 : "INTP",
        mbti2 : "ESTP",
        content : "상대방의 도전을 응원해주세요!",
    },
    {
        id : 168,
        mbti1 : "INTP",
        mbti2 : "ESTJ",
        content : "창의적인 아이디어로 도움을 주세요!",
    },
    {
        id : 169,
        mbti1 : "INTP",
        mbti2 : "INFP",
        content : "솔직함보다는 공감을 앞세워주세요! 놀라운 결과가 나타날 수도 있어요",
    },
    {
        id : 170,
        mbti1 : "INTP",
        mbti2 : "INFJ",
        content : "개인적인 시간도 좋지만 상대방과 커피 한잔 어떨까요?",
    },
    {
        id : 171,
        mbti1 : "INTP",
        mbti2 : "INTP",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 172,
        mbti1 : "INTP",
        mbti2 : "ISTP",
        content : "추상적인 생각보다는 현실적인 의견을 앞세워 말해주면 좋아해요!",
    },
    {
        id : 173,
        mbti1 : "INTP",
        mbti2 : "ISFP",
        content : "미래보다는 현상을 중요하게 생각해요!",
    },
    {
        id : 174,
        mbti1 : "INTP",
        mbti2 : "ISFJ",
        content : "직설적인 표현을 조금만 자제해볼까요?",
    },
    {
        id : 175,
        mbti1 : "INTP",
        mbti2 : "ISTJ",
        content : "목표가 분명한 사람이에요! 이상보다는 현상에 집중해주세요",
    },
    {
        id : 176,
        mbti1 : "INTP",
        mbti2 : "INTJ",
        content : "주관이 뚜렷한 편이에요! 의견을 존중해 주세요:)",
    },
    {
        id : 177,
        mbti1 : "ISTP",
        mbti2 : "ENFJ",
        content : "너무 솔직한 감정 표현은 상처를 줄 수 있어요",
    },
    {
        id : 178,
        mbti1 : "ISTP",
        mbti2 : "ENTJ",
        content : "집중해서 끝까지 일을 마무리할 수 있게 도와주세요!",
    },
    {
        id : 179,
        mbti1 : "ISTP",
        mbti2 : "ENFP",
        content : "상상력과 창의력이 뛰어나요! 아이디어가 필요할 때 도움을 청해보세요",
    },
    {
        id : 180,
        mbti1 : "ISTP",
        mbti2 : "ENTP",
        content : "창의력이 뛰어나요! 아이디어가 필요할 때 도움을 청해보세요",
    },
    {
        id : 181,
        mbti1 : "ISTP",
        mbti2 : "ESFP",
        content : "공감을 바탕으로 이야기한다면 좋은 아이디어를 얻을 수 있어요!",
    },
    {
        id : 182,
        mbti1 : "ISTP",
        mbti2 : "ESFJ",
        content : "지나치게 솔직한 표현은 상처를 줄 수 있어요!",
    },
    {
        id : 183,
        mbti1 : "ISTP",
        mbti2 : "ESTP",
        content : "사람과의 교류를 좋아해요! 관심을 한 번 표현해 주면 어떨까요?",
    },
    {
        id : 184,
        mbti1 : "ISTP",
        mbti2 : "ESTJ",
        content : "책임감이 강하고 효율을 중시합니다! 믿고 의지하면 좋은 결과를 얻을 수 있어요",
    },
    {
        id : 185,
        mbti1 : "ISTP",
        mbti2 : "INFP",
        content : "솔직함보다는 공감을 앞세워주세요!",
    },
    {
        id : 186,
        mbti1 : "ISTP",
        mbti2 : "INFJ",
        content : "새로운 방식으로 접근하는 것을 좋아해요! 의견을 존중해 주는 것이 어떨까요?",
    },
    {
        id : 187,
        mbti1 : "ISTP",
        mbti2 : "INTP",
        content : "관심 분야는 누구보다 적극적이에요! 용기를 낸다면 좋은 아이디어를 얻을 수 있을 거예요",
    },
    {
        id : 188,
        mbti1 : "ISTP",
        mbti2 : "ISTP",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 189,
        mbti1 : "ISTP",
        mbti2 : "ISFP",
        content : "협력과 조화를 중요하게 생각해요! 서로 배려해보는 게 어떨까요?",
    },
    {
        id : 190,
        mbti1 : "ISTP",
        mbti2 : "ISFJ",
        content : "지나치게 솔직한 표현은 상처를 줄 수 있어요!",
    },
    {
        id : 191,
        mbti1 : "ISTP",
        mbti2 : "ISTJ",
        content : "논리만 내세우기보다는 의견을 존중해주세요!",
    },
    {
        id : 192,
        mbti1 : "ISTP",
        mbti2 : "INTJ",
        content : "주관이 뚜렷한 편이에요! 의견을 존중해 주세요:)",
    },
    {
        id : 193,
        mbti1 : "ISFP",
        mbti2 : "ENFJ",
        content : "칭찬을 아끼지 마세요!",
    },
    {
        id : 194,
        mbti1 : "ISFP",
        mbti2 : "ENTJ",
        content : "넓은 포용력으로 직선적인 표현을 이해해 주세요!",
    },
    {
        id : 195,
        mbti1 : "ISFP",
        mbti2 : "ENFP",
        content : "창의력이 뛰어나요! 북돋아 주면 좋은 아이디어를 얻을 수 있어요",
    },
    {
        id : 196,
        mbti1 : "ISFP",
        mbti2 : "ENTP",
        content : "상대방의 도전을 응원해주세요!",
    },
    {
        id : 197,
        mbti1 : "ISFP",
        mbti2 : "ESFP",
        content : "관심이 많아서 그런 거예요! 놀라지 말아요",
    },
    {
        id : 198,
        mbti1 : "ISFP",
        mbti2 : "ESFJ",
        content : "친화력이 좋아서 그런 거예요! 놀라지 말아요",
    },
    {
        id : 199,
        mbti1 : "ISFP",
        mbti2 : "ESTP",
        content : "넓은 포용력으로 직선적인 표현을 이해해 주세요!",
    },
    {
        id : 200,
        mbti1 : "ISFP",
        mbti2 : "ESTJ",
        content : "고민이 될 때 열린 마음으로 조언을 구해봐요!",
    },
    {
        id : 201,
        mbti1 : "ISFP",
        mbti2 : "INFP",
        content : "상대방의 상상력을 존중해주세요!",
    },
    {
        id : 202,
        mbti1 : "ISFP",
        mbti2 : "INFJ",
        content : "말이 없을 때는 신중한 거예요! 먼저 말을 건네봐요",
    },
    {
        id : 203,
        mbti1 : "ISFP",
        mbti2 : "INTP",
        content : "개인적인 시간을 충분히 주세요!",
    },
    {
        id : 204,
        mbti1 : "ISFP",
        mbti2 : "ISTP",
        content : "위기 상황이 닥쳤을 때 도움을 청해봐요!",
    },
    {
        id : 205,
        mbti1 : "ISFP",
        mbti2 : "ISFP",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 206,
        mbti1 : "ISFP",
        mbti2 : "ISFJ",
        content : "완벽하면 좋잖아요! 옆에서 응원해 주세요:)",
    },
    {
        id : 207,
        mbti1 : "ISFP",
        mbti2 : "ISTJ",
        content : "완벽하면 좋잖아요! 옆에서 응원해 주세요:)",
    },
    {
        id : 208,
        mbti1 : "ISFP",
        mbti2 : "INTJ",
        content : "조심스럽게 다가가 열정을 본받아 보아요!",
    },
    {
        id : 209,
        mbti1 : "ISFJ",
        mbti2 : "ENFJ",
        content : "사람과의 교류를 좋아해요! 관심을 한 번 표현해 주면 어떨까요?",
    },
    {
        id : 210,
        mbti1 : "ISFJ",
        mbti2 : "ENTJ",
        content : "타고난 리더에요! 협조하면 긍정적인 시너지가 날 거예요",
    },
    {
        id : 211,
        mbti1 : "ISFJ",
        mbti2 : "ENFP",
        content : "창의력이 뛰어나요! 북돋아 주면 좋은 아이디어를 얻을 수 있어요",
    },
    {
        id : 212,
        mbti1 : "ISFJ",
        mbti2 : "ENTP",
        content : "혁신적인 일을 좋아해요! 다만, 일을 끝까지 잘 마무리할 수 있게 도와주세요!",
    },
    {
        id : 213,
        mbti1 : "ISFJ",
        mbti2 : "ESFP",
        content : "낙천적인 사람이에요! 관심을 한 번 표현해 주면 어떨까요?",
    },
    {
        id : 214,
        mbti1 : "ISFJ",
        mbti2 : "ESFJ",
        content : "사람과의 교류를 좋아해요! 관심을 한 번 표현해 주면 어떨까요?",
    },
    {
        id : 215,
        mbti1 : "ISFJ",
        mbti2 : "ESTP",
        content : "사람과의 교류를 좋아해요! 관심을 한 번 표현해 주면 어떨까요?",
    },
    {
        id : 216,
        mbti1 : "ISFJ",
        mbti2 : "ESTJ",
        content : "분명한 것을 좋아해요! 미래보다는 현상에 집중합니다",
    },
    {
        id : 217,
        mbti1 : "ISFJ",
        mbti2 : "INFP",
        content : "공감을 바탕으로 서포트해주면 놀라운 결과가 나타날 수도 있어요",
    },
    {
        id : 218,
        mbti1 : "ISFJ",
        mbti2 : "INFJ",
        content : "새로운 방식으로 접근하는 것을 좋아해요! 의견을 존중해 주는 것이 어떨까요?",
    },
    {
        id : 219,
        mbti1 : "ISFJ",
        mbti2 : "INTP",
        content : "분석하는 것을 좋아하는 사람이에요! 계획적으로 실행할 수 있도록 옆에서 도와주세요",
    },
    {
        id : 220,
        mbti1 : "ISFJ",
        mbti2 : "ISTP",
        content : "자유로운 환경 속에서 일의 능률이 올라요! 제한하기보다는 자유를 주세요",
    },
    {
        id : 221,
        mbti1 : "ISFJ",
        mbti2 : "ISFP",
        content : "집중해서 끝까지 일을 마무리할 수 있게 도와주세요!",
    },
    {
        id : 222,
        mbti1 : "ISFJ",
        mbti2 : "ISFJ",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 223,
        mbti1 : "ISFJ",
        mbti2 : "ISTJ",
        content : "논리만 내세우기보다는 의견을 존중해주세요!",
    },
    {
        id : 224,
        mbti1 : "ISFJ",
        mbti2 : "INTJ",
        content : "무엇인지 보다 왜인지를 중요하게 생각해요! 주관이 뚜렷하니 서로 의견 존중이 필요합니다",
    },
    {
        id : 225,
        mbti1 : "ISTJ",
        mbti2 : "ENFJ",
        content : "현실적인 계획으로 목표 달성에 도움을 주세요!",
    },
    {
        id : 226,
        mbti1 : "ISTJ",
        mbti2 : "ENTJ",
        content : "상대방의 도움을 열린 마음으로 받아보세요!",
    },
    {
        id : 227,
        mbti1 : "ISTJ",
        mbti2 : "ENFP",
        content : "현실적인 계획으로 목표 달성에 도움을 주세요!",
    },
    {
        id : 228,
        mbti1 : "ISTJ",
        mbti2 : "ENTP",
        content : "상대방의 도전을 응원해주세요!",
    },
    {
        id : 229,
        mbti1 : "ISTJ",
        mbti2 : "ESFP",
        content : "친화력이 좋아서 그런 거예요! 놀라지 말아요",
    },
    {
        id : 230,
        mbti1 : "ISTJ",
        mbti2 : "ESFJ",
        content : "상냥한 말로 우호적인 분위기를 만들어 보면 어떨까요?",
    },
    {
        id : 231,
        mbti1 : "ISTJ",
        mbti2 : "ESTP",
        content : "상대방의 도전을 응원해주세요!",
    },
    {
        id : 232,
        mbti1 : "ISTJ",
        mbti2 : "ESTJ",
        content : "서로 조금씩 양보한다면 최고의 파트너!",
    },
    {
        id : 233,
        mbti1 : "ISTJ",
        mbti2 : "INFP",
        content : "웃는 미소에 웃는 얼굴로 보답 하는 건 어떨까요?",
    },
    {
        id : 234,
        mbti1 : "ISTJ",
        mbti2 : "INFJ",
        content : "가끔 실수를 하더라도 이해해 주세요!",
    },
    {
        id : 235,
        mbti1 : "ISTJ",
        mbti2 : "INTP",
        content : "규칙과 자유로움 그 중간은 어떨까요?",
    },
    {
        id : 236,
        mbti1 : "ISTJ",
        mbti2 : "ISTP",
        content : "가끔 일이 안풀릴 때 도움을 청해봐요!",
    },
    {
        id : 237,
        mbti1 : "ISTJ",
        mbti2 : "ISFP",
        content : "체계적인 계획으로 도움을 건네봐요!",
    },
    {
        id : 238,
        mbti1 : "ISTJ",
        mbti2 : "ISFJ",
        content : "이야기를 듣고 공감부터 해주세요!",
    },
    {
        id : 239,
        mbti1 : "ISTJ",
        mbti2 : "ISTJ",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
    {
        id : 240,
        mbti1 : "ISTJ",
        mbti2 : "INTJ",
        content : "하나의 목표를 향해 같이 뭉쳐보는 건 어떨까요?",
    },
    {
        id : 241,
        mbti1 : "INTJ",
        mbti2 : "ENFJ",
        content : "너무 솔직한 감정 표현은 상처를 줄 수 있어요!",
    },
    {
        id : 242,
        mbti1 : "INTJ",
        mbti2 : "ENTJ",
        content : "거시적인 안목이 탁월해요! 장기적인 계획을 세울 때 분명 도움이 될 거예요",
    },
    {
        id : 243,
        mbti1 : "INTJ",
        mbti2 : "ENFP",
        content : "틀에 얽매이는 것을 싫어해요! 제한보다는 자유를 주세요",
    },
    {
        id : 244,
        mbti1 : "INTJ",
        mbti2 : "ENTP",
        content : "집중해서 끝까지 일을 마무리할 수 있게 도와주세요!",
    },
    {
        id : 245,
        mbti1 : "INTJ",
        mbti2 : "ESFP",
        content : "자유로운 환경 속에서 일의 능률이 올라요! 제한하기보다는 자유를 주세요",
    },
    {
        id : 246,
        mbti1 : "INTJ",
        mbti2 : "ESFJ",
        content : "의견을 먼저 내세우기 보다는 이야기를 들어주는 것이 중요해요!",
    },
    {
        id : 247,
        mbti1 : "INTJ",
        mbti2 : "ESTP",
        content : "자유로운 환경 속에서 일의 능률이 올라요! 제한하기보다는 자유를 주세요",
    },
    {
        id : 248,
        mbti1 : "INTJ",
        mbti2 : "ESTJ",
        content : "사람과의 대화를 좋아해요! 말 한 마디 건네보면 어떨까요?",
    },
    {
        id : 249,
        mbti1 : "INTJ",
        mbti2 : "INFP",
        content : "공감을 바탕으로 서포트해주면 놀라운 결과가 나타날 수도 있어요",
    },
    {
        id : 250,
        mbti1 : "INTJ",
        mbti2 : "INFJ",
        content : "솔직함보다는 공감을 앞세워주세요!",
    },
    {
        id : 251,
        mbti1 : "INTJ",
        mbti2 : "INTP",
        content : "분석하는 것을 좋아하는 사람이에요! 계획적으로 실행할 수 있도록 옆에서 도와주세요",
    },
    {
        id : 252,
        mbti1 : "INTJ",
        mbti2 : "ISTP",
        content : "자유로운 환경 속에서 일의 능률이 올라요! 제한하기보다는 자유를 주세요",
    },
    {
        id : 253,
        mbti1 : "INTJ",
        mbti2 : "ISFP",
        content : "통솔 받기보다는 화합하기를 좋아해요!",
    },
    {
        id : 254,
        mbti1 : "INTJ",
        mbti2 : "ISFJ",
        content : "이야기를 듣고 공감부터 해주세요!",
    },
    {
        id : 255,
        mbti1 : "INTJ",
        mbti2 : "ISTJ",
        content : "목표가 분명한 사람이에요! 이상보다는 현상에 집중해주세요",
    },
    {
        id : 256,
        mbti1 : "INTJ",
        mbti2 : "INTJ",
        content : "장점도 단점도 닮은 우리, 서로 조금만 배려해볼까요?",
    },
];


export {mbtiInfo, matchingInfo}